# -*- coding: utf-8 -*-
"""
/***************************************************************************
 WtyczkaDoProjektu2ZInformatyki
                                 A QGIS plugin
 WtyczkaDoProjektu2ZInformatyki
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-06-09
        copyright            : (C) 2023 by M.Wolańska, O. Śliwińska, K. Tokarski
        email                : martyna.wolanska13@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load WtyczkaDoProjektu2ZInformatyki class from file WtyczkaDoProjektu2ZInformatyki.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .proj_2 import WtyczkaDoProjektu2ZInformatyki
    return WtyczkaDoProjektu2ZInformatyki(iface)
